
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDleftNEGATIVEAND COMMA CONST DIMPLICATION IMPLICATION LETTERS LPAREN NEGATIVE OR RPARENexpr : LETTERSexpr : NEGATIVE exprexpr : LPAREN expr RPARENexpr : expr AND exprexpr : expr OR exprexpr : expr IMPLICATION exprexpr : expr DIMPLICATION expr'
    
_lr_action_items = {'LETTERS':([0,3,4,5,6,7,8,],[2,2,2,2,2,2,2,]),'NEGATIVE':([0,3,4,5,6,7,8,],[3,3,3,3,3,3,3,]),'LPAREN':([0,3,4,5,6,7,8,],[4,4,4,4,4,4,4,]),'$end':([1,2,9,11,12,13,14,15,],[0,-1,-2,-4,-5,-6,-7,-3,]),'AND':([1,2,9,10,11,12,13,14,15,],[5,-1,-2,5,-4,5,5,5,-3,]),'OR':([1,2,9,10,11,12,13,14,15,],[6,-1,-2,6,-4,-5,6,6,-3,]),'IMPLICATION':([1,2,9,10,11,12,13,14,15,],[7,-1,-2,7,-4,-5,7,7,-3,]),'DIMPLICATION':([1,2,9,10,11,12,13,14,15,],[8,-1,-2,8,-4,-5,8,8,-3,]),'RPAREN':([2,9,10,11,12,13,14,15,],[-1,-2,15,-4,-5,-6,-7,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,4,5,6,7,8,],[1,9,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> LETTERS','expr',1,'p_neg3','lexer.py',47),
  ('expr -> NEGATIVE expr','expr',2,'p_neg2','lexer.py',51),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_par','lexer.py',55),
  ('expr -> expr AND expr','expr',3,'p_andexp','lexer.py',59),
  ('expr -> expr OR expr','expr',3,'p_orexp','lexer.py',63),
  ('expr -> expr IMPLICATION expr','expr',3,'p_impli','lexer.py',67),
  ('expr -> expr DIMPLICATION expr','expr',3,'p_dimpli','lexer.py',71),
]
